routes/web.php
<?php
 
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
 
Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);
 
Route::group(['middleware' => 'auth'], function () {
 
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    
    Route::resource('posts', PostController::class);

    Route::get('profile', [ProfileController::class, 'index'])->name('profile');
    Route::post('profile', [ProfileController::class, 'profile']);
 
});
Route::get('home/{id}', [HomeController::class, 'posts'])->name('home.posts');

//TinyMCE
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('erd', [HomeController::class, 'home']);

Route::get('/posts/{id}/download', [PostController::class, 'download']);

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="col-md-4 offset-md-4 mt-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Form Login</h3>
                </div>
                <form action="{{ route('login') }}" method="post">
                @csrf
                <div class="card-body">
                    @if(session('errors'))
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            Something it's wrong:
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                            </ul>
                        </div>
                    @endif
                    @if (Session::has('success'))
                        <div class="alert alert-success">
                            {{ Session::get('success') }}
                        </div>
                    @endif
                    @if (Session::has('error'))
                        <div class="alert alert-danger">
                            {{ Session::get('error') }}
                        </div>
                    @endif
                    <div class="form-group">
                        <label for=""><strong>Email</strong></label>
                        <input type="text" name="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for=""><strong>Password</strong></label>
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-block">Log In</button>
                    <p class="text-center">Belum punya akun? <a href="{{ route('register') }}">Register</a> sekarang!</p>
                </div>
                </form>
            </div>
        </div>
    </div>
    @include('sweetalert::alert')
</body>
</html>

resources/views/profile.blade.php
@extends('adminlte.master')
@section('profile')

@section('content')


           
            <div class="card card-widget widget-user">
             
              <div class="widget-user-header     text-white" style="background: url({{asset('/adminlte/dist/img/photo1.png')}}) center center;">
                <h3 class="widget-user-username text-right">{{ Auth::user()->name }}</h3>
                <h5 class="widget-user-desc text-right">Web Designer</h5>
              </div>
              <div class="widget-user-image">
                <img class="img-circle" src="{{asset('/adminlte/dist/img/user2-160x160.jpg')}}" alt="User Avatar">
              </div>
              <div class="card-footer">
                <div class="row">
                  
                  <div class="col-sm-12">
                    <div class="description-block">
                      <b><span class="description-text">{{ Auth::user()->name }}</span></b> 
                    </div>

                  </div>
                  
                  
                </div>
              
              </div>
            </div>

          
            <div class="float-right ml-2 mr-3 mt-4">
                <a class="btn btn-secondary" href="{{ route('posts.index') }}"> Create</a>
            </div>
    

            <div class="float-right mr-3 ml-2 mt-4">
                <a class="btn btn-secondary" href="{{ route('posts.index') }}"> Update</a>
            </div>
            <br>
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Profil</h3>
              </div>
    
              <div class="card-body">
                <table class="table table-bordered">
                  <tbody>
                    <tr>
                      <td style="width: 3%">1.</td>
                      <td>Nama</td>
                      <td style="width: 55%">
                      @foreach ($profile as $object)
                        {{ $object->nama }}
                      @endforeach
                      </td>
                      
                    </tr>
                    <tr>
                      <td>2.</td>
                      <td>Alamat</td>
                      <td>
                      @foreach ($profile as $object)
                        {{ $object->alamat }}
                      @endforeach
                      </td>
                      
                    </tr>
                    <tr>
                      <td>3.</td>
                      <td>Jenis Kelamain</td>
                      <td>
                      @foreach ($profile as $object)
                        {{ $object->kelamin }}
                      @endforeach
                      </td>
                      
                    </tr>
                    <tr>
                      <td>4.</td>
                      <td>Kewarganeraan</td>
                      <td>
                      @foreach ($profile as $object)
                        {{ $object->kewarganegaraan}}
                      @endforeach
                      </td>
                      
                    </tr>
                    <tr>
                      <td>5.</td>
                      <td>Agama</td>
                      <td>
                      @foreach ($profile as $object)
                        {{ $object->agama }}
                      @endforeach
                      </td>
                      
                    </tr>
                  </tbody>
                </table>
              </div>
 
            </div>
    
@endsection

resources/views/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="col-md-4 offset-md-4 mt-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Form Register</h3>
                </div>
                <form action="{{ route('register') }}" method="post">
                @csrf
                <div class="card-body">
                    @if(session('errors'))
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            Something it's wrong:
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="form-group">
                        <label for=""><strong>Nama Lengkap</strong></label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Lengkap">
                    </div>
                    <div class="form-group">
                        <label for=""><strong>Email</strong></label>
                        <input type="text" name="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for=""><strong>Password</strong></label>
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label for=""><strong>Konfirmasi Password</strong></label>
                        <input type="password" name="password_confirmation" class="form-control" placeholder="Password">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-block">Register</button>
                    <p class="text-center">Sudah punya akun? <a href="{{ route('login') }}">Login</a> sekarang!</p>
                </div>
                </form>
            </div>
        </div>
    </div>
    @include('sweetalert::alert')
</body>
</html>